/**
 * Traducciones de nombres de países.
 * Clave: nombre en inglés (tal como viene de la DB / scraper).
 * Valor: { es, en, de }
 */
const countries = {
  "Abkhazia": { es: "Abjasia", en: "Abkhazia", de: "Abchasien" },
  "Afghanistan": { es: "Afganistán", en: "Afghanistan", de: "Afghanistan" },
  "Alaska": { es: "Alaska", en: "Alaska", de: "Alaska" },
  "Albania": { es: "Albania", en: "Albania", de: "Albanien" },
  "Algeria": { es: "Argelia", en: "Algeria", de: "Algerien" },
  "Andorra": { es: "Andorra", en: "Andorra", de: "Andorra" },
  "Angola": { es: "Angola", en: "Angola", de: "Angola" },
  "Antigua": { es: "Antigua", en: "Antigua", de: "Antigua" },
  "Argentina": { es: "Argentina", en: "Argentina", de: "Argentinien" },
  "Armenia": { es: "Armenia", en: "Armenia", de: "Armenien" },
  "Aruba": { es: "Aruba", en: "Aruba", de: "Aruba" },
  "Australia": { es: "Australia", en: "Australia", de: "Australien" },
  "Austria": { es: "Austria", en: "Austria", de: "Österreich" },
  "Azerbaijan": { es: "Azerbaiyán", en: "Azerbaijan", de: "Aserbaidschan" },
  "Azores": { es: "Azores", en: "Azores", de: "Azoren" },
  "Bahamas": { es: "Bahamas", en: "Bahamas", de: "Bahamas" },
  "Bahrain": { es: "Baréin", en: "Bahrain", de: "Bahrain" },
  "Bangladesh": { es: "Bangladés", en: "Bangladesh", de: "Bangladesch" },
  "Barbados": { es: "Barbados", en: "Barbados", de: "Barbados" },
  "Belarus": { es: "Bielorrusia", en: "Belarus", de: "Belarus" },
  "Belgium": { es: "Bélgica", en: "Belgium", de: "Belgien" },
  "Belize": { es: "Belice", en: "Belize", de: "Belize" },
  "Benin": { es: "Benín", en: "Benin", de: "Benin" },
  "Bermuda": { es: "Bermudas", en: "Bermuda", de: "Bermuda" },
  "Bhutan": { es: "Bután", en: "Bhutan", de: "Bhutan" },
  "Biafra": { es: "Biafra", en: "Biafra", de: "Biafra" },
  "Bolivia": { es: "Bolivia", en: "Bolivia", de: "Bolivien" },
  "Bosnia Herzegovina": { es: "Bosnia Herzegovina", en: "Bosnia Herzegovina", de: "Bosnien-Herzegowina" },
  "Botswana": { es: "Botsuana", en: "Botswana", de: "Botswana" },
  "Brazil": { es: "Brasil", en: "Brazil", de: "Brasilien" },
  "British Caribbean Territories": { es: "Territorios Británicos del Caribe", en: "British Caribbean Territories", de: "Britische Karibikgebiete" },
  "British Honduras": { es: "Honduras Británica", en: "British Honduras", de: "Britisch-Honduras" },
  "British West Africa": { es: "África Occidental Británica", en: "British West Africa", de: "Britisch-Westafrika" },
  "Brunei": { es: "Brunéi", en: "Brunei", de: "Brunei" },
  "Bulgaria": { es: "Bulgaria", en: "Bulgaria", de: "Bulgarien" },
  "Burkina Faso": { es: "Burkina Faso", en: "Burkina Faso", de: "Burkina Faso" },
  "Burma": { es: "Birmania", en: "Burma", de: "Burma" },
  "Burundi": { es: "Burundi", en: "Burundi", de: "Burundi" },
  "Cambodia": { es: "Camboya", en: "Cambodia", de: "Kambodscha" },
  "Cameroon": { es: "Camerún", en: "Cameroon", de: "Kamerun" },
  "Canada": { es: "Canadá", en: "Canada", de: "Kanada" },
  "Cape Verde": { es: "Cabo Verde", en: "Cape Verde", de: "Kap Verde" },
  "Cayman Islands": { es: "Islas Caimán", en: "Cayman Islands", de: "Kaimaninseln" },
  "Central African Republic": { es: "República Centroafricana", en: "Central African Republic", de: "Zentralafrikanische Republik" },
  "Central African States": { es: "Estados Centroafricanos", en: "Central African States", de: "Zentralafrikanische Staaten" },
  "Ceylon": { es: "Ceilán", en: "Ceylon", de: "Ceylon" },
  "Chad": { es: "Chad", en: "Chad", de: "Tschad" },
  "Chile": { es: "Chile", en: "Chile", de: "Chile" },
  "China": { es: "China", en: "China", de: "China" },
  "Colombia": { es: "Colombia", en: "Colombia", de: "Kolumbien" },
  "Comoros": { es: "Comoras", en: "Comoros", de: "Komoren" },
  "Confederate States Of America": { es: "Estados Confederados de América", en: "Confederate States Of America", de: "Konföderierte Staaten von Amerika" },
  "Congo": { es: "Congo", en: "Congo", de: "Kongo" },
  "Congo Democratic Republic": { es: "República Democrática del Congo", en: "Congo Democratic Republic", de: "Demokratische Republik Kongo" },
  "Cook Islands": { es: "Islas Cook", en: "Cook Islands", de: "Cookinseln" },
  "Costa Rica": { es: "Costa Rica", en: "Costa Rica", de: "Costa Rica" },
  "Croatia": { es: "Croacia", en: "Croatia", de: "Kroatien" },
  "Cuba": { es: "Cuba", en: "Cuba", de: "Kuba" },
  "Curacao": { es: "Curazao", en: "Curacao", de: "Curaçao" },
  "Cyprus": { es: "Chipre", en: "Cyprus", de: "Zypern" },
  "Czechia": { es: "Chequia", en: "Czechia", de: "Tschechien" },
  "Czechoslovakia": { es: "Checoslovaquia", en: "Czechoslovakia", de: "Tschechoslowakei" },
  "Danish West Indies": { es: "Indias Occidentales Danesas", en: "Danish West Indies", de: "Dänisch-Westindien" },
  "Danzig": { es: "Danzig", en: "Danzig", de: "Danzig" },
  "Denmark": { es: "Dinamarca", en: "Denmark", de: "Dänemark" },
  "Djibouti": { es: "Yibuti", en: "Djibouti", de: "Dschibuti" },
  "Dominica": { es: "Dominica", en: "Dominica", de: "Dominica" },
  "Dominican Republic": { es: "República Dominicana", en: "Dominican Republic", de: "Dominikanische Republik" },
  "East Africa": { es: "África Oriental", en: "East Africa", de: "Ostafrika" },
  "East Caribbean States": { es: "Estados del Caribe Oriental", en: "East Caribbean States", de: "Ostkaribische Staaten" },
  "Ecuador": { es: "Ecuador", en: "Ecuador", de: "Ecuador" },
  "Egypt": { es: "Egipto", en: "Egypt", de: "Ägypten" },
  "El Salvador": { es: "El Salvador", en: "El Salvador", de: "El Salvador" },
  "Equatorial African States": { es: "Estados de África Ecuatorial", en: "Equatorial African States", de: "Äquatorialafrikanische Staaten" },
  "Equatorial Guinea": { es: "Guinea Ecuatorial", en: "Equatorial Guinea", de: "Äquatorialguinea" },
  "Eritrea": { es: "Eritrea", en: "Eritrea", de: "Eritrea" },
  "Estonia": { es: "Estonia", en: "Estonia", de: "Estland" },
  "Eswatini": { es: "Esuatini", en: "Eswatini", de: "Eswatini" },
  "Ethiopia": { es: "Etiopía", en: "Ethiopia", de: "Äthiopien" },
  "European Central Bank": { es: "Banco Central Europeo", en: "European Central Bank", de: "Europäische Zentralbank" },
  "Faeroe Islands": { es: "Islas Feroe", en: "Faeroe Islands", de: "Färöer-Inseln" },
  "Falkland Islands": { es: "Islas Malvinas", en: "Falkland Islands", de: "Falklandinseln" },
  "Federal Republic Of Germany": { es: "República Federal de Alemania", en: "Federal Republic Of Germany", de: "Bundesrepublik Deutschland" },
  "Fiji": { es: "Fiyi", en: "Fiji", de: "Fidschi" },
  "Finland": { es: "Finlandia", en: "Finland", de: "Finnland" },
  "Fiume": { es: "Fiume", en: "Fiume", de: "Fiume" },
  "France": { es: "Francia", en: "France", de: "Frankreich" },
  "French Antilles": { es: "Antillas Francesas", en: "French Antilles", de: "Französische Antillen" },
  "French Equatorial Africa": { es: "África Ecuatorial Francesa", en: "French Equatorial Africa", de: "Französisch-Äquatorialafrika" },
  "French Guiana": { es: "Guayana Francesa", en: "French Guiana", de: "Französisch-Guayana" },
  "French India": { es: "India Francesa", en: "French India", de: "Französisch-Indien" },
  "French Indochina": { es: "Indochina Francesa", en: "French Indochina", de: "Französisch-Indochina" },
  "French Oceania": { es: "Oceanía Francesa", en: "French Oceania", de: "Französisch-Ozeanien" },
  "French Pacific Territories": { es: "Territorios Franceses del Pacífico", en: "French Pacific Territories", de: "Französische Pazifikgebiete" },
  "French Somaliland": { es: "Somalia Francesa", en: "French Somaliland", de: "Französisch-Somaliland" },
  "French West Africa": { es: "África Occidental Francesa", en: "French West Africa", de: "Französisch-Westafrika" },
  "Gabon": { es: "Gabón", en: "Gabon", de: "Gabun" },
  "Gambia": { es: "Gambia", en: "Gambia", de: "Gambia" },
  "Georgia": { es: "Georgia", en: "Georgia", de: "Georgien" },
  "German Democratic Republic": { es: "República Democrática Alemana", en: "German Democratic Republic", de: "Deutsche Demokratische Republik" },
  "German East Africa": { es: "África Oriental Alemana", en: "German East Africa", de: "Deutsch-Ostafrika" },
  "German Southwest Africa": { es: "África del Suroeste Alemana", en: "German Southwest Africa", de: "Deutsch-Südwestafrika" },
  "Germany": { es: "Alemania", en: "Germany", de: "Deutschland" },
  "Ghana": { es: "Ghana", en: "Ghana", de: "Ghana" },
  "Gibraltar": { es: "Gibraltar", en: "Gibraltar", de: "Gibraltar" },
  "Great Britain": { es: "Gran Bretaña", en: "Great Britain", de: "Großbritannien" },
  "Greece": { es: "Grecia", en: "Greece", de: "Griechenland" },
  "Greenland": { es: "Groenlandia", en: "Greenland", de: "Grönland" },
  "Grenada": { es: "Granada", en: "Grenada", de: "Grenada" },
  "Guadeloupe": { es: "Guadalupe", en: "Guadeloupe", de: "Guadeloupe" },
  "Guatemala": { es: "Guatemala", en: "Guatemala", de: "Guatemala" },
  "Guernsey": { es: "Guernsey", en: "Guernsey", de: "Guernsey" },
  "Guinea": { es: "Guinea", en: "Guinea", de: "Guinea" },
  "Guinea Bissau": { es: "Guinea-Bisáu", en: "Guinea Bissau", de: "Guinea-Bissau" },
  "Guyana": { es: "Guyana", en: "Guyana", de: "Guyana" },
  "Haiti": { es: "Haití", en: "Haiti", de: "Haiti" },
  "Hawaii": { es: "Hawái", en: "Hawaii", de: "Hawaii" },
  "Honduras": { es: "Honduras", en: "Honduras", de: "Honduras" },
  "Hong Kong": { es: "Hong Kong", en: "Hong Kong", de: "Hongkong" },
  "Hungary": { es: "Hungría", en: "Hungary", de: "Ungarn" },
  "Iceland": { es: "Islandia", en: "Iceland", de: "Island" },
  "India": { es: "India", en: "India", de: "Indien" },
  "Indonesia": { es: "Indonesia", en: "Indonesia", de: "Indonesien" },
  "Iran": { es: "Irán", en: "Iran", de: "Iran" },
  "Iraq": { es: "Irak", en: "Iraq", de: "Irak" },
  "Ireland": { es: "Irlanda", en: "Ireland", de: "Irland" },
  "Isle Of Man": { es: "Isla de Man", en: "Isle Of Man", de: "Isle of Man" },
  "Israel": { es: "Israel", en: "Israel", de: "Israel" },
  "Italian East Africa": { es: "África Oriental Italiana", en: "Italian East Africa", de: "Italienisch-Ostafrika" },
  "Italian Somaliland": { es: "Somalia Italiana", en: "Italian Somaliland", de: "Italienisch-Somaliland" },
  "Italy": { es: "Italia", en: "Italy", de: "Italien" },
  "Ivory Coast": { es: "Costa de Marfil", en: "Ivory Coast", de: "Elfenbeinküste" },
  "Jamaica": { es: "Jamaica", en: "Jamaica", de: "Jamaika" },
  "Japan": { es: "Japón", en: "Japan", de: "Japan" },
  "Jersey": { es: "Jersey", en: "Jersey", de: "Jersey" },
  "Jordan": { es: "Jordania", en: "Jordan", de: "Jordanien" },
  "Katanga": { es: "Katanga", en: "Katanga", de: "Katanga" },
  "Kazakhstan": { es: "Kazajistán", en: "Kazakhstan", de: "Kasachstan" },
  "Kenya": { es: "Kenia", en: "Kenya", de: "Kenia" },
  "Korea": { es: "Corea", en: "Korea", de: "Korea" },
  "Korea North": { es: "Corea del Norte", en: "Korea North", de: "Nordkorea" },
  "Korea South": { es: "Corea del Sur", en: "Korea South", de: "Südkorea" },
  "Kuwait": { es: "Kuwait", en: "Kuwait", de: "Kuwait" },
  "Kyrgyzstan": { es: "Kirguistán", en: "Kyrgyzstan", de: "Kirgisistan" },
  "Laos": { es: "Laos", en: "Laos", de: "Laos" },
  "Latvia": { es: "Letonia", en: "Latvia", de: "Lettland" },
  "Lebanon": { es: "Líbano", en: "Lebanon", de: "Libanon" },
  "Lesotho": { es: "Lesoto", en: "Lesotho", de: "Lesotho" },
  "Liberia": { es: "Liberia", en: "Liberia", de: "Liberia" },
  "Libya": { es: "Libia", en: "Libya", de: "Libyen" },
  "Liechtenstein": { es: "Liechtenstein", en: "Liechtenstein", de: "Liechtenstein" },
  "Lithuania": { es: "Lituania", en: "Lithuania", de: "Litauen" },
  "Luxembourg": { es: "Luxemburgo", en: "Luxembourg", de: "Luxemburg" },
  "Macau": { es: "Macao", en: "Macau", de: "Macau" },
  "Macedonia": { es: "Macedonia", en: "Macedonia", de: "Mazedonien" },
  "Madagascar": { es: "Madagascar", en: "Madagascar", de: "Madagaskar" },
  "Malawi": { es: "Malaui", en: "Malawi", de: "Malawi" },
  "Malaya": { es: "Malaya", en: "Malaya", de: "Malaya" },
  "Malaya And British Borneo": { es: "Malaya y Borneo Británico", en: "Malaya And British Borneo", de: "Malaya und Britisch-Borneo" },
  "Malaysia": { es: "Malasia", en: "Malaysia", de: "Malaysia" },
  "Maldives": { es: "Maldivas", en: "Maldives", de: "Malediven" },
  "Mali": { es: "Malí", en: "Mali", de: "Mali" },
  "Malta": { es: "Malta", en: "Malta", de: "Malta" },
  "Martinique": { es: "Martinica", en: "Martinique", de: "Martinique" },
  "Mauritania": { es: "Mauritania", en: "Mauritania", de: "Mauretanien" },
  "Mauritius": { es: "Mauricio", en: "Mauritius", de: "Mauritius" },
  "Mexico": { es: "México", en: "Mexico", de: "Mexiko" },
  "Moldova": { es: "Moldavia", en: "Moldova", de: "Moldawien" },
  "Monaco": { es: "Mónaco", en: "Monaco", de: "Monaco" },
  "Mongolia": { es: "Mongolia", en: "Mongolia", de: "Mongolei" },
  "Montenegro": { es: "Montenegro", en: "Montenegro", de: "Montenegro" },
  "Montserrat": { es: "Montserrat", en: "Montserrat", de: "Montserrat" },
  "Morocco": { es: "Marruecos", en: "Morocco", de: "Marokko" },
  "Mozambique": { es: "Mozambique", en: "Mozambique", de: "Mosambik" },
  "Myanmar": { es: "Myanmar", en: "Myanmar", de: "Myanmar" },
  "Namibia": { es: "Namibia", en: "Namibia", de: "Namibia" },
  "Nepal": { es: "Nepal", en: "Nepal", de: "Nepal" },
  "Netherlands": { es: "Países Bajos", en: "Netherlands", de: "Niederlande" },
  "Netherlands Antilles": { es: "Antillas Neerlandesas", en: "Netherlands Antilles", de: "Niederländische Antillen" },
  "Netherlands Indies": { es: "Indias Orientales Neerlandesas", en: "Netherlands Indies", de: "Niederländisch-Indien" },
  "New Caledonia": { es: "Nueva Caledonia", en: "New Caledonia", de: "Neukaledonien" },
  "New Hebrides": { es: "Nuevas Hébridas", en: "New Hebrides", de: "Neue Hebriden" },
  "New Zealand": { es: "Nueva Zelanda", en: "New Zealand", de: "Neuseeland" },
  "Newfoundland": { es: "Terranova", en: "Newfoundland", de: "Neufundland" },
  "Nicaragua": { es: "Nicaragua", en: "Nicaragua", de: "Nicaragua" },
  "Niger": { es: "Níger", en: "Niger", de: "Niger" },
  "Nigeria": { es: "Nigeria", en: "Nigeria", de: "Nigeria" },
  "Northern Ireland": { es: "Irlanda del Norte", en: "Northern Ireland", de: "Nordirland" },
  "Norway": { es: "Noruega", en: "Norway", de: "Norwegen" },
  "Oman": { es: "Omán", en: "Oman", de: "Oman" },
  "Pakistan": { es: "Pakistán", en: "Pakistan", de: "Pakistan" },
  "Palestine": { es: "Palestina", en: "Palestine", de: "Palästina" },
  "Panama": { es: "Panamá", en: "Panama", de: "Panama" },
  "Papua New Guinea": { es: "Papúa Nueva Guinea", en: "Papua New Guinea", de: "Papua-Neuguinea" },
  "Paraguay": { es: "Paraguay", en: "Paraguay", de: "Paraguay" },
  "Peru": { es: "Perú", en: "Peru", de: "Peru" },
  "Philippines": { es: "Filipinas", en: "Philippines", de: "Philippinen" },
  "Poland": { es: "Polonia", en: "Poland", de: "Polen" },
  "Portugal": { es: "Portugal", en: "Portugal", de: "Portugal" },
  "Portuguese Guinea": { es: "Guinea Portuguesa", en: "Portuguese Guinea", de: "Portugiesisch-Guinea" },
  "Portuguese India": { es: "India Portuguesa", en: "Portuguese India", de: "Portugiesisch-Indien" },
  "Qatar": { es: "Catar", en: "Qatar", de: "Katar" },
  "Qatar And Dubai": { es: "Catar y Dubái", en: "Qatar And Dubai", de: "Katar und Dubai" },
  "Reunion": { es: "Reunión", en: "Reunion", de: "Réunion" },
  "Rhodesia": { es: "Rodesia", en: "Rhodesia", de: "Rhodesien" },
  "Romania": { es: "Rumanía", en: "Romania", de: "Rumänien" },
  "Russia": { es: "Rusia", en: "Russia", de: "Russland" },
  "Rwanda": { es: "Ruanda", en: "Rwanda", de: "Ruanda" },
  "Rwanda Burundi": { es: "Ruanda-Burundi", en: "Rwanda Burundi", de: "Ruanda-Burundi" },
  "Saar": { es: "Sarre", en: "Saar", de: "Saarland" },
  "Saint Helena": { es: "Santa Elena", en: "Saint Helena", de: "St. Helena" },
  "Saint Lucia": { es: "Santa Lucía", en: "Saint Lucia", de: "St. Lucia" },
  "Saint Pierre & Miquelon": { es: "San Pedro y Miquelón", en: "Saint Pierre & Miquelon", de: "Saint-Pierre und Miquelon" },
  "Saint Vincent": { es: "San Vicente", en: "Saint Vincent", de: "St. Vincent" },
  "Samoa": { es: "Samoa", en: "Samoa", de: "Samoa" },
  "San Marino": { es: "San Marino", en: "San Marino", de: "San Marino" },
  "Sao Tome E Principe": { es: "Santo Tomé y Príncipe", en: "Sao Tome E Principe", de: "São Tomé und Príncipe" },
  "Sarawak": { es: "Sarawak", en: "Sarawak", de: "Sarawak" },
  "Saudi Arabia": { es: "Arabia Saudita", en: "Saudi Arabia", de: "Saudi-Arabien" },
  "Scotland": { es: "Escocia", en: "Scotland", de: "Schottland" },
  "Senegal": { es: "Senegal", en: "Senegal", de: "Senegal" },
  "Serbia": { es: "Serbia", en: "Serbia", de: "Serbien" },
  "Seychelles": { es: "Seychelles", en: "Seychelles", de: "Seychellen" },
  "Siam": { es: "Siam", en: "Siam", de: "Siam" },
  "Sierra Leone": { es: "Sierra Leona", en: "Sierra Leone", de: "Sierra Leone" },
  "Singapore": { es: "Singapur", en: "Singapore", de: "Singapur" },
  "Slovakia": { es: "Eslovaquia", en: "Slovakia", de: "Slowakei" },
  "Slovenia": { es: "Eslovenia", en: "Slovenia", de: "Slowenien" },
  "Solomon Islands": { es: "Islas Salomón", en: "Solomon Islands", de: "Salomonen" },
  "Somalia": { es: "Somalia", en: "Somalia", de: "Somalia" },
  "Somaliland": { es: "Somalilandia", en: "Somaliland", de: "Somaliland" },
  "South Africa": { es: "Sudáfrica", en: "South Africa", de: "Südafrika" },
  "South Sudan": { es: "Sudán del Sur", en: "South Sudan", de: "Südsudan" },
  "Southern Rhodesia": { es: "Rodesia del Sur", en: "Southern Rhodesia", de: "Südrhodesien" },
  "Southwest Africa": { es: "África del Suroeste", en: "Southwest Africa", de: "Südwestafrika" },
  "Soviet Union": { es: "Unión Soviética", en: "Soviet Union", de: "Sowjetunion" },
  "Spain": { es: "España", en: "Spain", de: "Spanien" },
  "Sri Lanka": { es: "Sri Lanka", en: "Sri Lanka", de: "Sri Lanka" },
  "Straits Settlements": { es: "Establecimientos del Estrecho", en: "Straits Settlements", de: "Straits Settlements" },
  "Sudan": { es: "Sudán", en: "Sudan", de: "Sudan" },
  "Suriname": { es: "Surinam", en: "Suriname", de: "Suriname" },
  "Sweden": { es: "Suecia", en: "Sweden", de: "Schweden" },
  "Switzerland": { es: "Suiza", en: "Switzerland", de: "Schweiz" },
  "Syria": { es: "Siria", en: "Syria", de: "Syrien" },
  "Tahiti": { es: "Tahití", en: "Tahiti", de: "Tahiti" },
  "Taiwan": { es: "Taiwán", en: "Taiwan", de: "Taiwan" },
  "Tajikistan": { es: "Tayikistán", en: "Tajikistan", de: "Tadschikistan" },
  "Tanzania": { es: "Tanzania", en: "Tanzania", de: "Tansania" },
  "Thailand": { es: "Tailandia", en: "Thailand", de: "Thailand" },
  "Timor": { es: "Timor", en: "Timor", de: "Timor" },
  "Togo": { es: "Togo", en: "Togo", de: "Togo" },
  "Tonga": { es: "Tonga", en: "Tonga", de: "Tonga" },
  "Transnistria": { es: "Transnistria", en: "Transnistria", de: "Transnistrien" },
  "Trinidad And Tobago": { es: "Trinidad y Tobago", en: "Trinidad And Tobago", de: "Trinidad und Tobago" },
  "Tunisia": { es: "Túnez", en: "Tunisia", de: "Tunesien" },
  "Turkey": { es: "Turquía", en: "Turkey", de: "Türkei" },
  "Turkmenistan": { es: "Turkmenistán", en: "Turkmenistan", de: "Turkmenistan" },
  "Turks And Caicos Islands": { es: "Islas Turcas y Caicos", en: "Turks And Caicos Islands", de: "Turks- und Caicosinseln" },
  "Uganda": { es: "Uganda", en: "Uganda", de: "Uganda" },
  "Ukraine": { es: "Ucrania", en: "Ukraine", de: "Ukraine" },
  "United Arab Emirates": { es: "Emiratos Árabes Unidos", en: "United Arab Emirates", de: "Vereinigte Arabische Emirate" },
  "United States Of America": { es: "Estados Unidos", en: "United States Of America", de: "Vereinigte Staaten von Amerika" },
  "Uruguay": { es: "Uruguay", en: "Uruguay", de: "Uruguay" },
  "Uzbekistan": { es: "Uzbekistán", en: "Uzbekistan", de: "Usbekistan" },
  "Vanuatu": { es: "Vanuatu", en: "Vanuatu", de: "Vanuatu" },
  "Vatican City": { es: "Ciudad del Vaticano", en: "Vatican City", de: "Vatikanstadt" },
  "Venezuela": { es: "Venezuela", en: "Venezuela", de: "Venezuela" },
  "Vietnam": { es: "Vietnam", en: "Vietnam", de: "Vietnam" },
  "West African States": { es: "Estados de África Occidental", en: "West African States", de: "Westafrikanische Staaten" },
  "Yemen": { es: "Yemen", en: "Yemen", de: "Jemen" },
  "Yugoslavia": { es: "Yugoslavia", en: "Yugoslavia", de: "Jugoslawien" },
  "Zaire": { es: "Zaire", en: "Zaire", de: "Zaire" },
  "Zambia": { es: "Zambia", en: "Zambia", de: "Sambia" },
  "Zanzibar": { es: "Zanzíbar", en: "Zanzibar", de: "Sansibar" },
  "Zimbabwe": { es: "Zimbabue", en: "Zimbabwe", de: "Simbabwe" },
};

/**
 * Traduce un nombre de país del inglés al idioma indicado.
 * Si no encuentra traducción, devuelve el nombre original.
 */
export function translateCountry(englishName, locale) {
  const entry = countries[englishName];
  if (!entry) return englishName;
  return entry[locale] || entry.en || englishName;
}

/**
 * Dado un nombre traducido y un locale, devuelve el nombre en inglés (para filtrar en la DB).
 * Búsqueda inversa.
 */
export function countryToEnglish(translatedName, locale) {
  for (const [en, translations] of Object.entries(countries)) {
    if (translations[locale] === translatedName) return en;
  }
  return translatedName;
}

/**
 * Devuelve la lista completa de países traducidos al locale dado, ordenados alfabéticamente.
 */
export function getAllCountriesTranslated(englishNames, locale) {
  return englishNames
    .map(en => ({ en, translated: translateCountry(en, locale) }))
    .sort((a, b) => a.translated.localeCompare(b.translated, locale));
}

export default countries;
